TheRealGioviok/Perseus-Engine

src/evaluation.cpp
src/search.cpp

Elo   | 31.59 +- 12.26 (95%)
LLR   | 2.94 (-2.94, 2.94) [0.00, 5.00]
Games | N: 1886 W: 736 L: 565 D: 585
Penta | [67, 173, 344, 240, 119]
https://perseusopenbench.pythonanywhere.com/test/16/
bench 7512775

Tentative values for king safety (tuning will be very difficult)

---

src/Position.cpp
src/Position.h
src/search.cpp
src/tables.cpp

Elo   | 45.22 +- 14.07 (95%)
Games | N: 1190 W: 422 L: 268 D: 500
Penta | [20, 111, 220, 183, 61]
https://perseusopenbench.pythonanywhere.com/test/34/

bench 4783435

---

src/Game.cpp
src/Position.cpp
src/Position.h
src/evaluation.cpp
src/history.cpp
src/history.h
src/search.cpp
src/zobrist.cpp
src/zobrist.h

Elo   | 16.11 +- 7.87 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 5.00]
Games | N: 3302 W: 1018 L: 865 D: 1419
Penta | [69, 346, 699, 437, 100]
https://perseusopenbench.pythonanywhere.com/test/98/

Add Pawn Corrhist

---

src/search.cpp

Elo   | 5.25 +- 3.92 (95%)
Games | N: 12770 W: 3586 L: 3393 D: 5791
Penta | [274, 1478, 2719, 1609, 305]
https://perseusopenbench.pythonanywhere.com/test/117/
bench 6832271

bench 6832271

---

src/Game.cpp
src/Game.h
src/Position.cpp
src/Position.h
src/history.cpp
src/history.h
src/search.cpp
src/zobrist.cpp
src/zobrist.h

Elo   | 6.32 +- 4.47 (95%)
Games | N: 10064 W: 2910 L: 2727 D: 4427
Penta | [201, 1229, 2050, 1290, 262]
https://perseusopenbench.pythonanywhere.com/test/126/
bench 5582536

Minorcorrhist

---

README.md
src/search.cpp

Elo   | 6.24 +- 4.42 (95%)
Games | N: 10022 W: 2874 L: 2694 D: 4454
Penta | [209, 1140, 2185, 1216, 261]
https://perseusopenbench.pythonanywhere.com/test/144/
bench 4482752

Add granular improvement condition for lmr

---

README.md
src/search.cpp
src/tables.cpp
src/tables.h

Bring up to date

---

src/constants.cpp
src/constants.h
src/makefile
src/tables.cpp
src/uci.cpp

Fixed Makefile clean command to remove both Debug and Release intermediate files

---

src/evaluation.cpp

Elo   | 7.98 +- 5.25 (95%)
Games | N: 7620 W: 2340 L: 2165 D: 3115
Penta | [200, 827, 1592, 980, 211]
https://perseusopenbench.pythonanywhere.com/test/186/

bench 4803710

---

src/movegen.h

small speedup

---

src/search.cpp

Elo   | 4.12 +- 3.24 (95%)
Games | N: 18566 W: 5514 L: 5294 D: 7758
Penta | [397, 2143, 4052, 2225, 466]
https://perseusopenbench.pythonanywhere.com/test/301/
bench 3674052

Reduce depth on root fail-high

---

src/search.cpp

Elo   | 53.48 +- 14.57 (95%)
Games | N: 956 W: 357 L: 211 D: 388
Penta | [11, 74, 190, 164, 39]
https://perseusopenbench.pythonanywhere.com/test/308/

AHAHAHAHHAHAAHAHAHHAHAHAHHAHAHAHHAHAHAHHAHAHAHAHHAHHAHAHHAHAHHAHAHAHAHA :)

---

src/Position.cpp
src/Position.h

Very small speedup and unused code removal

---

src/Position.cpp
src/Position.h
src/evaluation.cpp
src/history.cpp
src/history.h
src/movegen.h
src/search.cpp

Elo   | 2.88 +- 2.32 (95%)
Games | N: 34226 W: 9652 L: 9368 D: 15206
Penta | [665, 3976, 7544, 4266, 662]
https://perseusopenbench.pythonanywhere.com/test/339/

Threats indexed quiets history

---

src/Position.cpp
src/Position.h
src/history.cpp
src/history.h
src/search.cpp
src/zobrist.cpp
src/zobrist.h

Elo   | 5.49 +- 3.95 (95%)
LLR   | 3.01 (-2.94, 2.94) [0.00, 5.00]
Games | N: 11326 W: 3169 L: 2990 D: 5167
Penta | [174, 1328, 2520, 1427, 214]
https://perseusopenbench.pythonanywhere.com/test/357/

King Rook Pawn Corrhist

---

src/Game.h
src/bench.cpp
src/search.cpp
src/uci.cpp

Finally we can debug crashes in OB (hopefully).
bench 3379758

added exact go nodes (still using old nodes counting system)

---

src/tt.h
src/uci.cpp

CURSE OF RA 𓀀 𓀁 𓀂 𓀃 𓀄 𓀅 𓀆 𓀇 𓀈 𓀉 𓀊 𓀋 𓀌 𓀍 𓀎 𓀏 𓀐 𓀑 𓀒 𓀓 𓀔 𓀕 𓀖 𓀗 𓀘 𓀙 𓀚 𓀛 𓀜 𓀝 𓀞 𓀟 𓀠 𓀡 𓀢 𓀣 𓀤 𓀥 𓀦 𓀧 𓀨 𓀩 𓀪 𓀫 𓀬 𓀭 𓀮 𓀯 𓀰 𓀱 𓀲 𓀳 𓀴 𓀵 𓀶 𓀷 𓀸 𓀹 𓀺 𓀻 𓀼 𓀽 𓀾 𓀿 𓁀 𓁁 𓁂 𓁃 𓁄 𓁅 𓁆 𓁇 𓁈 𓁉 𓁊 𓁋 𓁌 𓁍 𓁎 𓁏 𓁐 𓁑 𓀄 𓀅 𓀆

fix large TT sizes

---

src/Game.cpp
src/Game.h
src/bench.cpp
src/search.cpp
src/tt.cpp
src/tt.h
src/uci.cpp

Elo   | 0.87 +- 1.84 (95%)
LLR   | 2.95 (-2.94, 2.94) [-3.00, 0.00]
Games | N: 37586 W: 9905 L: 9811 D: 17870
Penta | [357, 3729, 10501, 3875, 331]
https://perseusopenbench.pythonanywhere.com/test/472/
bench 2414819

Aging without iterating the whole tt

---

src/build.mk
src/history.h
src/search.cpp
src/tables.cpp

Elo   | 1.63 +- 1.30 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 3.00]
Games | N: 95506 W: 25178 L: 24730 D: 45598
Penta | [1223, 11507, 21953, 11739, 1331]
https://pyronomy.pythonanywhere.com/test/1857/
bench 2893632

Uncursed hh lmr for noisy moves

---

src/evaluation.cpp

Clean, idiomatic rewrite of pawn eval and threats eval
