TheRealGioviok/Perseus-Engine

- src/Game.cpp
- src/constants.h
- src/evaluation.cpp
- src/search.cpp
- src/tt.cpp
- src/tt.h
```
Finished tournament.
Results of TEST vs DEV:
Elo: 24.90 +/- 10.53, nElo: 33.86 +/- 14.27
LOS: 100.00 %, DrawRatio: 39.16 %, PairsRatio: 1.39
Games: 2278, Wins: 786, Losses: 623, Draws: 869, Points: 1220.5 (53.58 %)
Ptnml(0-2): [68, 222, 446, 285, 118]
LLR: 2.96 (-2.94, 2.94) [0.00, 5.00]
```
`bench: 3951396`
Fixed history reductions, optimized away some ifs, removed ancient styled Delta pruning in qsearch, removed unused variables and code
> Fixed hh reductions / extensions / optimization / cleanuppery

- .gitignore
- src/build.mk
- src/makefile
As per title, the general file structure of the Makefile has been updated to follow a cleaner standard. This structure caches the object files and allows the system to understand which file needs to be regenerated, speeding up compilation times.
It also adds the possibility to specify the compiler with `make CXX=<>` and the name of the executable with `make EXE=<>` as per OpenBench standard.
---
Nodes: 9297401 (unchanged)
> Improved makefile structure and cached intermediate files to speed up compilations

- src/search.cpp
Elo   | 9.45 +- 5.77 (95%)
Games | N: 5958 W: 1716 L: 1554 D: 2688
Penta | [114, 697, 1238, 773, 157]
https://perseusopenbench.pythonanywhere.com/test/37/
> bench 2608848

- src/search.cpp
Elo   | 17.45 +- 8.16 (95%)
LLR   | 3.02 (-2.94, 2.94) [0.00, 5.00]
Games | N: 3068 W: 921 L: 767 D: 1380
Penta | [55, 341, 628, 415, 95]
https://perseusopenbench.pythonanywhere.com/test/124/
bench 5691931
> bench 5691931

- src/search.cpp
Elo   | 7.74 +- 5.10 (95%)
Games | N: 7768 W: 2247 L: 2074 D: 3447
Penta | [180, 873, 1619, 1018, 194]
https://perseusopenbench.pythonanywhere.com/test/132/
> bench 5194389

- src/Position.cpp
Ty to @Ciekce for the suggestion
Elo   | 6.64 +- 4.61 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
Games | N: 9524 W: 2870 L: 2688 D: 3966
Penta | [222, 1065, 2039, 1181, 255]
https://perseusopenbench.pythonanywhere.com/test/192/
> Introduce adaptive SEE threshold

- src/search.cpp
Elo   | 23.81 +- 9.07 (95%)
LLR   | 3.05 (-2.94, 2.94) [0.00, 5.00]
Games | N: 1944 W: 589 L: 456 D: 899
Penta | [12, 202, 434, 289, 35]
https://perseusopenbench.pythonanywhere.com/test/208/
> History based moveloop pruning

- src/constants.h
- src/search.cpp
Elo   | 4.45 +- 3.45 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 5.00]
Games | N: 16948 W: 4953 L: 4736 D: 7259
Penta | [416, 1915, 3602, 2118, 423]
https://perseusopenbench.pythonanywhere.com/test/212/
> bench 3662095

- src/constants.h
- src/search.cpp
Passed STC:
Elo   | 7.33 +- 4.91 (95%)
Games | N: 8054 W: 2415 L: 2245 D: 3394
Penta | [163, 919, 1723, 1029, 193]
https://perseusopenbench.pythonanywhere.com/test/216/
Passed LTC:
Elo   | 13.91 +- 6.89 (95%)
SPRT  | 60.0+0.60s Threads=1 Hash=64MB
Games | N: 3398 W: 981 L: 845 D: 1572
Penta | [42, 348, 792, 466, 51]
https://perseusopenbench.pythonanywhere.com/test/217/
bench 4284744
> Indian tune

- src/evaluation.cpp
- src/evaluation.h
- src/search.cpp
- src/tables.cpp
- src/tables.h
Elo   | 5.63 +- 4.09 (95%)
LLR   | 3.02 (-2.94, 2.94) [0.00, 5.00]
Games | N: 12164 W: 3642 L: 3445 D: 5077
Penta | [286, 1387, 2584, 1494, 331]
https://perseusopenbench.pythonanywhere.com/test/267/
> Precomputed ks tables

- src/Position.cpp
- src/Position.h
Elo   | 2.36 +- 1.76 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 5.00]
Games | N: 62676 W: 18355 L: 17929 D: 26392
Penta | [1441, 7165, 13730, 7531, 1471]
https://perseusopenbench.pythonanywhere.com/test/273/
> Ordering++

- src/search.cpp
Now with non bugged elo:
Passed STC:
Elo   | 7.41 +- 4.93 (95%)
Games | N: 7972 W: 2372 L: 2202 D: 3398
Penta | [154, 916, 1726, 986, 204]
https://perseusopenbench.pythonanywhere.com/test/291/
Passed LTC:
Elo   | 3.58 +- 2.84 (95%)
SPRT  | 40.0+0.40s Threads=1 Hash=64MB
Games | N: 20480 W: 5676 L: 5465 D: 9339
Penta | [288, 2370, 4745, 2517, 320]
https://perseusopenbench.pythonanywhere.com/test/292/
> bench 4328000

- src/Game.cpp
- src/Position.cpp
- src/Position.h
- src/evaluation.cpp
- src/evaluation.h
- src/search.cpp
Elo   | 13.65 +- 7.02 (95%)
Games | N: 3718 W: 1169 L: 1023 D: 1526
Penta | [65, 373, 867, 459, 95]
https://perseusopenbench.pythonanywhere.com/test/295/
> Pawn eval hash

- src/search.cpp
Elo   | 6.98 +- 4.73 (95%)
Games | N: 8514 W: 2497 L: 2326 D: 3691
Penta | [177, 940, 1867, 1081, 192]
https://perseusopenbench.pythonanywhere.com/test/320/
>  Do deeper / shallower zero window lmr research based on score and lmr depth

- src/search.cpp
Elo   | 3.09 +- 2.49 (95%)
Games | N: 30342 W: 8661 L: 8391 D: 13290
Penta | [581, 3633, 6552, 3745, 660]
https://perseusopenbench.pythonanywhere.com/test/326/
> Negative extension on failed singular cutnodes

- src/evaluation.cpp
Nonregr
Elo   | 0.97 +- 2.29 (95%)
SPRT  | 8.0+0.08s Threads=1 Hash=32MB
LLR   | 2.96 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 35198 W: 9795 L: 9697 D: 15706
Penta | [669, 4256, 7663, 4330, 681]
https://perseusopenbench.pythonanywhere.com/test/338/
> Fix TempoInFormula

- src/Game.cpp
- src/Position.cpp
- src/Position.h
- src/history.cpp
- src/history.h
- src/search.cpp
- src/zobrist.cpp
- src/zobrist.h
Generalization of common correction techniques such as major / minor and an original KRP (also called rook endgames corrhist).
Try all the KXY triplets, with X != Y, and both X and Y different than K.
This also is very nice from a tunability standpoint.
(Some "mean shift" effect are being suspected with the introduction of this many corrhists, but they seem to be outweighted by the sheer gain).
Passed STC:
Elo   | 18.82 +- 8.49 (95%)
Games | N: 2698 W: 873 L: 727 D: 1098
Penta | [43, 289, 573, 367, 77]
https://perseusopenbench.pythonanywhere.com/test/361/
Passed LTC:
Elo   | 21.94 +- 8.72 (95%)
SPRT  | 60.0+0.60s Threads=1 Hash=64MB
Games | N: 2014 W: 641 L: 514 D: 859 …
> Add Triplet Correction History / UberCorrection History

- src/search.cpp
Elo   | 3.28 +- 2.63 (95%)
LLR   | 2.99 (-2.94, 2.94) [0.00, 5.00]
Games | N: 26976 W: 7797 L: 7542 D: 11637
Penta | [532, 3138, 5926, 3327, 565]
https://perseusopenbench.pythonanywhere.com/test/376/
bench 3445600
> Always search at least one move in pvs

- src/history.cpp
- src/history.h
Really powerful tweak by @mcthouacbb . Seems to reduce strange corrhists score biases.
Elo   | 4.76 +- 3.62 (95%)
Games | N: 14164 W: 4144 L: 3950 D: 6070
Penta | [248, 1689, 3069, 1773, 303]
https://perseusopenbench.pythonanywhere.com/test/377/
bench 3379758
> Clamp Maximum Corrhist Update

- src/constants.h
- src/history.cpp
- src/history.h
Elo   | 2.81 +- 2.25 (95%)
Games | N: 36416 W: 10370 L: 10075 D: 15971
Penta | [673, 4340, 7974, 4461, 760]
https://perseusopenbench.pythonanywhere.com/test/398/
> Saner and separated history bonus/malus formula

- src/Position.cpp
- src/history.cpp
- src/history.h
One of the most curious thing to ever happen in Perseus.
Introduce FromTo threats capture history. Tests for indexing using only [from](https://perseusopenbench.pythonanywhere.com/test/414/) or [to](https://perseusopenbench.pythonanywhere.com/test/415/) were fails. To date, it is by far the longest test ever needed (game number wise).
Elo   | 1.66 +- 1.32 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 3.00]
Games | N: 104202 W: 29713 L: 29215 D: 45274
Penta | [1940, 12359, 23141, 12585, 2076]
https://perseusopenbench.pythonanywhere.com/test/413/
bench 3483966
> Introduce FromTo threats indexing in capture history.

- src/search.cpp
Elo   | 7.85 +- 4.08 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 3.00]
Games | N: 10754 W: 3122 L: 2879 D: 4753
Penta | [181, 1209, 2378, 1404, 205]
https://perseusopenbench.pythonanywhere.com/test/419/
bench 2935014
> Add tt depth IIR condition and avoid double reductions on pvcutnodes

- src/constants.h
- src/search.cpp
Elo   | 14.87 +- 5.75 (95%)
Games | N: 5212 W: 1585 L: 1362 D: 2265
Penta | [78, 513, 1237, 664, 114]
https://perseusopenbench.pythonanywhere.com/test/420/
bench 2378582
> Add PVS SEE pruning

- src/Game.cpp
Elo   | 3.37 +- 2.42 (95%)
Games | N: 29724 W: 8284 L: 7996 D: 13444
Penta | [522, 3379, 6731, 3749, 481]
https://perseusopenbench.pythonanywhere.com/test/432/
bench 2594815
> Add simple material phase to the final eval based on SEE values

- src/Position.h
- src/history.cpp
- src/history.h
- src/search.cpp
Elo   | 2.69 +- 2.06 (95%)
Games | N: 41016 W: 11207 L: 10890 D: 18919
Penta | [663, 4848, 9177, 5149, 671]
https://perseusopenbench.pythonanywhere.com/test/439/
bench 2618694
> 50 mr eval scaling

- src/Position.cpp
- src/Position.h
- src/history.cpp
- src/history.h
Elo   | 3.06 +- 2.84 (95%)
LLR   | 2.98 (-2.94, 2.94) [-3.00, 0.00]
Games | N: 16694 W: 4613 L: 4466 D: 7615
Penta | [160, 1686, 4535, 1779, 187]
https://perseusopenbench.pythonanywhere.com/test/458/
bench 2460917
> Use 16 bit arrays for histories

- src/search.cpp
Elo   | 2.33 +- 1.83 (95%)
Games | N: 50716 W: 13825 L: 13485 D: 23406
Penta | [799, 5962, 11474, 6346, 777]
https://perseusopenbench.pythonanywhere.com/test/462/
bench 2463447
> Removed thingy (sad)

- src/search.cpp
Very nice idea from [Obsidian](https://github.com/gab8192/Obsidian).
Elo   | 5.10 +- 3.12 (95%)
Games | N: 16684 W: 4496 L: 4251 D: 7937
Penta | [195, 1975, 3810, 2114, 248]
https://perseusopenbench.pythonanywhere.com/test/473/
bench 2466815
> Obsidian style qsearch incheck pruning

- src/constants.h
- src/search.cpp
Elo   | 2.22 +- 1.76 (95%)
LLR   | 2.94 (-2.94, 2.94) [0.00, 3.00]
Games | N: 52566 W: 14076 L: 13740 D: 24750
Penta | [673, 6287, 12079, 6519, 725]
https://perseusopenbench.pythonanywhere.com/test/485/
bench 2409759
> Add SEE based futility pruning in quiescence search

- src/search.cpp
Elo   | 5.15 +- 3.16 (95%)
Games | N: 16796 W: 4608 L: 4359 D: 7829
Penta | [245, 1909, 3865, 2110, 269]
https://perseusopenbench.pythonanywhere.com/test/486/
bench 2484355
> Change move pruning order and add some guards

- src/constants.h
- src/search.cpp
Elo   | 6.55 +- 3.60 (95%)
LLR   | 3.00 (-2.94, 2.94) [0.00, 3.00]
Games | N: 12736 W: 3465 L: 3225 D: 6046
Penta | [165, 1457, 2913, 1639, 194]
https://perseusopenbench.pythonanywhere.com/test/492/
bench 2845904
> Nmp static eval margin conditions

- src/constants.h
- src/search.cpp
Elo   | 1.45 +- 1.13 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 3.00]
Games | N: 127502 W: 33969 L: 33438 D: 60095
Penta | [1729, 15199, 29456, 15546, 1821]
https://perseusopenbench.pythonanywhere.com/test/495/
bench 2734344
> more negext for non pvnodes

- src/search.cpp
Passed nonregression STC
Elo   | 5.54 +- 3.80 (95%)
LLR   | 2.96 (-2.94, 2.94) [-3.00, 0.00]
Games | N: 10718 W: 2857 L: 2686 D: 5175
Penta | [122, 1217, 2504, 1400, 116]
https://pyronomy.pythonanywhere.com/test/1853/
bench 2897568
> Remove double extension limit and ply guard

- src/history.h
Elo   | 2.52 +- 1.94 (95%)
Games | N: 42720 W: 11196 L: 10886 D: 20638
Penta | [539, 5066, 9891, 5274, 590]
https://pyronomy.pythonanywhere.com/test/1938/
bench 2862801
> Apply movecount scaling before correction history

- src/constants.h
- src/search.cpp
Elo   | 1.85 +- 1.49 (95%)
Games | N: 72672 W: 19200 L: 18814 D: 34658
Penta | [935, 8646, 16820, 8968, 967]
https://pyronomy.pythonanywhere.com/test/2042/
bench 2884595
> IIR more in pv nodes and less in non pv nodes

- src/search.cpp
Elo   | 2.56 +- 1.96 (95%)
Games | N: 40948 W: 10688 L: 10386 D: 19874
Penta | [460, 4892, 9527, 5076, 519]
https://pyronomy.pythonanywhere.com/test/2128/
bench 2813920
> Reduce more in Null Move Pruning when improving

- src/evaluation.cpp
Its cursed that previous passed. Anywasy this clearly scales.
Elo   | 0.22 +- 1.58 (95%)
LLR   | 2.95 (-2.94, 2.94) [-3.00, 0.00]
Games | N: 63256 W: 16707 L: 16667 D: 29882
Penta | [790, 7609, 14767, 7695, 767]
https://perseusopenbench.pythonanywhere.com/test/501/
bench 2546128
> Consistent cached pawn eval block for passed pawns
